jobs:
- job: WebAppDI
  strategy:
    matrix:
      Debug:
        buildConfiguration: Debug
      Release:
        buildConfiguration: Release
  pool:
    vmImage: $(vmImageName)
  variables:
  - template: variables.WebAppDI.yml
  steps:

  - task: UseDotNet@2
    displayName: 'Install .NET 9 SDK'
    inputs:
      version: '9.0.0-preview.1.24081.2'
      includePreviewVersions: true
      performMultiLevelLookup: true
    
  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: restore
      projects: '$(projectName).sln'
      feedsToUse: 'config'
      nugetConfigPath: 'NuGet.config'
      includeNuGetOrg: true
  
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: build
      projects: '$(projectName).sln'
      arguments: '--configuration $(buildConfiguration) --no-restore /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(Build.ArtifactStagingDirectory)/$(projectName).zip"'
  
  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    inputs:
      command: test
      projects: '**/*Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration) --no-build'
    condition: and(succeeded(), eq(variables['buildConfiguration'], 'Debug'))

  - task: PublishPipelineArtifact@0
    displayName: publish pipeline artifact
    inputs:
      artifactName: $(projectName)/$(buildConfiguration)
      targetPath: $(Build.ArtifactStagingDirectory)
